run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  gosec:
    excludes:
      - G104
  govet:
    check-shadowing: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocyclo
    - dupl
    - gosec
    - unconvert
    - unparam
