FROM golang:1.22-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY cmd/init3dxui/main.go ./main.go
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /app/init ./main.go

FROM alpine:3.19
RUN apk --no-cache add ca-certificates=20250911-r0
WORKDIR /app
COPY --from=builder /app/init /app/init
USER 1000:1000
CMD ["/app/init"]
